name = "Reflectance"
uuid = "ce658124-c64e-440a-9f45-0760740a6285"
authors = ["Shem-RÄz Kaenan Idrees <shem.idrees@bnc.ox.ac.uk> and contributors"]
version = "1.0.0-DEV"

[deps]
Chain = "8be319e6-bccf-4806-a6f7-6fae938471bc"

[compat]
Chain = "0.6.0"
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
